### ISSUE TITLE
windwos 2016 Unlimited restart

### ISSUE THREAD

**Issue by OmniStage-AI** [mantechnology/bsr#2]
After compiling with the latest cygwin of vs2019 wdk10, it will be packaged as an installation package. After windows 2016 is installed, it will be prompted that the system will restart indefinitely, and the system will not be able to enter the safe mode. The termination code is: INACCESSIBLE BOOT DEVICE

**Comment by sungeun-kim** [comment]
Hello, late reply.

I think the kernel driver you built might be not signed. Also, in Win10 2019 or later, if secure boot is enabled, signing with an EV certificate is required.

Thank you.

**Comment by OmniStage-AI** [comment]
Hello!

This machine has enabled "test mode" and "ignore certificate startup", which is the same error.

**Comment by OmniStage-AI** [comment]
KDTARGET: Refreshing KD connection

*** Fatal System Error: 0x0000007b
                       (0xFFFFBF0049E31810,0xFFFFFFFFC0000034,0x0000000000000000,0x0000000000000000)

Break instruction exception - code 80000003 (first chance)

A fatal system error has occurred.
Debugger entered on first try; Bugcheck callbacks have not been invoked.

**Comment by sungeun-kim** [comment]
Hi,

I don't know if there are any other issues other than sign or secure boot issues. The build switch may have an effect during the compilation process of visual studio, which is difficult to explain in detail.

Below is a link to a package we recently created. If there is no problem by installing this package, you can think that there is some problem in your compilation environment, and if our package also crashes, we will treat it as an urgent issue.

Thank you.

[bsr 1.6-A12 packages](https://mantech.jira.com/wiki/download/attachments/2829746211/BSR_windows-x64_1_6(2021_06_03_A12).exe?version=1&modificationDate=1624842813060&cacheVersion=1&api=v2)

**Comment by OmniStage-AI** [comment]
Hello!

Thank you very much for your reply. There is no problem using your installation package to start. Hello, can you provide your compiling environment?

Thank you very much again, thank you!

**Comment by sungeun-kim** [comment]
We are using Visual Studio 2013 and 2016. To get the switch of the compiler and linker for builds, you can load the contents of the vsproj project file uploaded to git and use it as it is.

In fact, there are no special options or parts to build the kernel driver. So it's hard to guess where your driver load failure is coming from.

**Comment by zrma-gd** [comment]
Hello!

Thank you for your answer. At present, we use 2013 and wdk8.1 to compile and install. At present, the machine can restart and the service is up. Thank you!

At present, there is an error prompt when executing bsradm.exe

Unable to locate program input point uname_ X in DLL  C:\Program Files\bsr\bin\bsradm.exe.

**Comment by OmniStage-AI** [comment]
Hello!

Thank you very much for your answer. The problem has been solved.

thank you!
