### ISSUE TITLE
get the BSR User's Guide-English

### ISSUE THREAD

**Issue by BiuDoom** [mantechnology/bsr#6]
How do I get the BSR User's Guide-English?
Thank you!

**Comment by sungeun-kim** [comment]
Hi, 

Check out the link on the page below.

https://github.com/mantechnology/bsr/wiki

thank you.

**Comment by BiuDoom** [comment]
Thanks for your reply!
I tried clicking on the link in the wiki, but access required permission when I signed in.
This is the link. https://mantech.jira.com/wiki/spaces/BUGE/

**Comment by sungeun-kim** [comment]
sorry
Previously, anonymous viewing was allowed, but Atlassian seems to have changed something. I'll get back to you after I've looked into the settings and made anonymous viewing allowed.
thank you

**Comment by sungeun-kim** [comment]
You could be able to read the manual now.

**Comment by BiuDoom** [comment]
Ok,Thank you very much!
